# ThaiGlow LITE v5
dynamicHandLight=false

# ==========================================
# ⚙️  หน้าตั้งค่า: Options > Video Settings > Shaders > Shader Options
# ==========================================
screen=ENABLE_SUNMOON ENABLE_CLOUDS ENABLE_FOG ENABLE_DIRLIGHT

option.ENABLE_SUNMOON=Sun + Moon
option.ENABLE_SUNMOON.comment=Show / hide sun and moon
option.ENABLE_SUNMOON.values=1 0
option.ENABLE_SUNMOON.default=1
option.ENABLE_SUNMOON.value.1=ON
option.ENABLE_SUNMOON.value.0=OFF

option.ENABLE_CLOUDS=Clouds
option.ENABLE_CLOUDS.comment=Show / hide clouds
option.ENABLE_CLOUDS.values=1 0
option.ENABLE_CLOUDS.default=1
option.ENABLE_CLOUDS.value.1=ON
option.ENABLE_CLOUDS.value.0=OFF

option.ENABLE_FOG=Fog
option.ENABLE_FOG.comment=Show / hide distance fog
option.ENABLE_FOG.values=1 0
option.ENABLE_FOG.default=1
option.ENABLE_FOG.value.1=ON
option.ENABLE_FOG.value.0=OFF

option.ENABLE_DIRLIGHT=Directional Light
option.ENABLE_DIRLIGHT.comment=Enable / disable directional shading
option.ENABLE_DIRLIGHT.values=1 0
option.ENABLE_DIRLIGHT.default=1
option.ENABLE_DIRLIGHT.value.1=ON
option.ENABLE_DIRLIGHT.value.0=OFF
